---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: proxytoxi
  namespace: {{ .Release.Namespace | default "default"}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: proxytoxi-read
rules:
- apiGroups: [""]
  resources:
  - services
  - pods
  verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: proxytoxi-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: v-read
subjects:
- kind: ServiceAccount
  name: proxytoxi
  namespace: {{ .Release.Namespace | default "default"}}
---
